# -*- coding: utf-8 -*-
"""Vending_machine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjKUwrBzQQkRp92dmxH-L0eyktTnWrSB
"""

"""code with main() function."""
# Define the products and their prices using 3-digit codes
products = {"001": ("Coke", 1.50), "002": ("Sprite", 1.25), "003": ("Water", 1.00), "004": ("Chips", 0.75), "005": ("Chocolate", 1.25), "006": ("Gum", 0.50)}

# Define the initial inventory for each product
inventory = {"001": 10, "002": 10, "003": 10, "004": 10, "005": 10, "006": 10}


def main():
  # Main program
  display_products() 
  selection = input("Select a product (enter 3-digit code) (type 'e' to exit): ")
  while selection != "e":
      if selection not in products:
          print("Invalid selection.")
      elif inventory[selection] == 0:
          print("Out of stock.")
      else:
          product, price = products[selection]
          print(f"Price: ${price:.2f}")
          amount_paid = float(input("Insert amount: "))
          if amount_paid < price:
              print("Insufficient funds.")
          else:
              change = make_change(price, amount_paid)
              update_inventory(selection)
              print(f"Thank you for purchasing {product}")
              if change != 0: 
                print(f"Change: ${change:.2f}")
              print(f"Inventory available for {product}: {inventory[selection]}")
              print("----------------")

      # Display products and prompt for next selection
      selection = input("Select a product (enter 3-digit code) (type 'e' to exit): ")
  
# Function to display the products and their prices
def display_products():
    print("Products available:")
    for code, (product, price) in products.items():
        print(f"{code}: {product} - ${price:.2f} - {inventory[code]} items available")       

# Function to update the inventory
def update_inventory(code):
    inventory[code] -= 1

# Function to make change
def make_change(price, amount_paid):
    change = amount_paid - price
    return change

main()

